# Generated by Django 4.2.7 on 2023-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='Test', max_length=128),
            preserve_default=False,
        ),
    ]
