# Generated by Django 4.2.7 on 2023-12-01 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dg_app', '0002_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('graph_type', models.CharField(choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('hist', 'Histogram'), ('scatter', 'Scatter Plot'), ('area', 'Area Chart'), ('bubble', 'Bubble Chart'), ('box', 'Box-and-Whisker Plot'), ('radar', 'Radar Chart'), ('heatmap', 'Heatmap'), ('treemap', 'Treemap'), ('network', 'Network Graph')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('y_axis', models.IntegerField()),
                ('x_axis', models.IntegerField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dg_app.table')),
            ],
        ),
    ]
